### ISSUE TITLE
Cannot pip install on Windows 7

### ISSUE THREAD

**Issue by okkhoy** [spotify/annoy#293]
- I downloaded the VC++ 9 compiler + build tools necessary to install Python 2.7 packages. 
- Tried `pip install annoy`

The build fails with the following: `error C3861: '__popcnt64': identifier not found`

```
c:<>\local\temp\pip-build-jmpbob\annoy\src\annoylib.h(350) : error C3861: '__popcnt64': identifier not found
          c:<>\local\temp\pip-build-jmpbob\annoy\src\annoylib.h(714) : see reference to function template instantiation 'T Hamming::distance<S,T>(const Hamming::Node<S,T> *,const Hamming::Node<S,T> *,int)' being compiled
          with
          [
              T=uint64_t,
              S=int32_t
          ]
          c:<>\local\temp\pip-build-jmpbob\annoy\src\annoylib.h(713) : while compiling class template member function 'uint64_t AnnoyIndex<S,T,Distance,Random>::get_distance(S,S)'
          with
          [
              S=int32_t,
              T=uint64_t,
              Distance=Hamming,
              Random=Kiss64Random
          ]
```

there are a whole lot of warnings on improper type conversion in between

```
 error: command 'C:<>\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\amd64\\cl.exe' failed with exit status 2

  ----------------------------------------
  Failed building wheel for annoy
```

- Python version:
```
c:\> python --version
Python 2.7.14 :: Anaconda, Inc.
```

**Comment by eric-kimbrel** [comment]
same for windows 10

**Comment by simon19891101** [comment]
Anyone knows how to solve it? Cheers.

**Comment by tjrileywisc** [comment]
This should work for python 3.x, on any OS (I've used it on Win 7 and Win 10 without issues). 

I was never able to get this to build on Python 2.7 unfortunately when I worked on adding Windows support.

**Comment by rbares** [comment]
After testing with a popcnt64 implementation from Sean Anderson's "Bit Twiddling Hacks", handling some further missing identifiers and adding a couple of static casts I finally got this building. Unfortunately my build currently crashes during nosetests but will let you know if I get any further.

**Comment by erikbern** [comment]
@rbares do you have some alternative code for `__popcount64`? i guess we can provide an alternative implementation for visual studio using a preprocessor directive

**Comment by rbares** [comment]
Yes indeed that is the approach in my current implementation, although I have also forced its use in linux for comparison.

I was implementing `__popcount64` with the generalized approach [suggested by Eric Cole](https://graphics.stanford.edu/~seander/bithacks.html#CountBitsSetParallel), i.e:
```c
v = v - ((v >> 1) & (T)~(T)0/3);
v = (v & (T)~(T)0/15*3) + ((v >> 2) & (T)~(T)0/15*3);
v = (v + (v >> 4)) & (T)~(T)0/255*15;
c = (T)(v * ((T)~(T)0/255)) >> (sizeof(T) - 1) * CHAR_BIT;
```
but moved to:
```cpp
std::bitset<numeric_limits<T>::digits>(v).count()
```

Two problems:
- Crash in angular_index_test test_no_items. Temporarily disabled for now.
- Test failures in hamming_index_test for any case of `assertAlmostEqual(numpy.dot(...))`. These do not appear to be related to `popcount`, as when using `std::bitset` on linux these tests pass fine.

Both will benefit from reproducible test cases and stepping through the intermediate calculations. Happy to push up a WIP if that will help.

**Comment by erikbern** [comment]
pull request is very welcome @rbares !
